[package]
name = "timetable"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "./src/mod.rs"

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
chrono = "0.4.19"
chrono-tz = "0.6.1"
poem-openapi = { version = "2.0.4", features = ["bson", "chrono"] }
kuchiki = "0.8.1"
bson = { version = "2.3.0", features = ["chrono-0_4"] }
