[package]
name = "timetable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "./src/timetable.rs"

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
kuchiki = "0.8.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
poem = "1.2.59"
poem-openapi = "1.2.59"
chrono = { version = "0.4.19", features = ["serde"] }
bson={version="2.1.0",features=["chrono-0_4"]}
wither="0.9.0"