version = 1

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "./pjatk-api/Dockerfile",
    "./pjatk-schedule/Dockerfile"
  ]

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "1.59.1"

[[analyzers]]
name = "shell"
enabled = true