version: '3.9'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
  database-viewer:
    image: mongo-express
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "8081:8081"
  geckodriver:
    image: blueimp/geckodriver
    shm_size: 2g
    environment:
      MOZ_HEADLESS: 1
    ports:
      - 4444:4444
  # pjatk-api:
  #   build:
  #     dockerfile: pjatk-api/Dockerfile
  #     context: .
  #   ports:
  #     - 3000:3001
  # pjatk-schedule:
  #   build: .\pjatk-schedule\.
  #   ports:
  #     - 3000:3002
  
