version: '3.9'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  database-viewer:
    image: mongo-express
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8081:8081"
  geckodriver:
    image: instrumentisto/geckodriver:92.0-driver0.29.1
    shm_size: 2g
    environment:
      MOZ_HEADLESS: 1
    ports:
      - 4444:4444
    depends_on:
    - pjatk-scraper
    restart: unless-stopped
  pjatk-api:
    build:
      dockerfile: pjatk-api/Dockerfile
      context: .
    ports:
      - ${PJATK_API_PORT}:${PJATK_API_PORT}
    env_file:
      - .env
  pjatk-scraper:
    build: 
      dockerfile: pjatk-schedule/Dockerfile
      context: .
    ports:
      - ${PJATK_SCRAPPER_PORT}:${PJATK_SCRAPPER_PORT}
    env_file:
      - .env
    
    restart: unless-stopped
  
