name: Docker CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.toml'
      - '**.rs'
      - '**.lock'
      - '**.js'
      - '.dockerignore'
      - '**/Dockerfile'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  REG_USER: "pjatk21"
  IMAGE_NAME_1: "pjatk-api"
  IMAGE_NAME_2: "pjatk-schedule"

# Gonna die because of this 💀
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Build and push `pjatk-api`
        id: build-and-push-api
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: .
          push_git_tag: true
          dockerfile: ./${{ env.IMAGE_NAME_1 }}/Dockerfile
          image_tag: latest
          image_name: pjatk-api
      
      - name: Build and push `pjatk-scraper`
        id: build-and-push-scraper
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: .
          push_git_tag: true
          dockerfile: ./${{ env.IMAGE_NAME_2 }}/Dockerfile
          image_tag: latest
          image_name: pjatk-scraper
