name: Rust

on:
  workflow_dispatch:
  
  pull_request:
    branches: [ main ]
    paths:
      - '**.toml'
      - '**.rs'
      - '**.lock'
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Rust nightly
      run: rustup default nightly

    - name: Update toolcahin
      run: rustup update

    - name: Install `clippy`
      run: rustup component add clippy

    - name: Lint code in workspace
      run: cargo clippy --workspace
